import type { Candidate } from "./types";

const base = (
  partial: Omit<Candidate, "snapshot"> & { snapshot?: Candidate["snapshot"] }
): Candidate => ({
  snapshot: null,
  ...partial,
});

export function fixtureCandidates(): Candidate[] {
  return [
    base({
      recordId: "PRC-0001",
      name: "Priya M.",
      email: "priya@example.com",
      phone: "+91 98765 43210",
      meditatorStatus: "Regular",
      ageGroup: "25–34",
      region: "India",
      occupation: "Designer",
      priorFeedback: "",
      featureTag: "Practices",
      status: null,
      callCount: 0,
      lastContactedAt: null,
      scratchpad: "",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0002",
      name: "James O.",
      email: "james@example.co.uk",
      phone: "+44 7700 900123",
      meditatorStatus: "New",
      ageGroup: "35–44",
      region: "UK",
      occupation: "Teacher",
      priorFeedback: "Shared feedback in March",
      featureTag: "Practices",
      status: "No answer",
      callCount: 2,
      lastContactedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      scratchpad: "Tried twice, no pickup",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0003",
      name: "Anita R.",
      email: "anita@example.com",
      phone: "+91 91234 56789",
      meditatorStatus: "Regular",
      ageGroup: "45–54",
      region: "India",
      occupation: "Engineer",
      priorFeedback: "",
      featureTag: "Practices",
      status: "Interviewed",
      callCount: 1,
      lastContactedAt: new Date().toISOString(),
      scratchpad: "Warm call",
      postCallSummary: "Uses morning practices daily.",
      snapshot: {
        quickFacts: {
          name: "Anita R.",
          ageGroup: "45–54",
          region: "India",
          meditatorStatus: "Regular",
          occupation: "Engineer",
          interviewDate: new Date().toISOString().slice(0, 10),
        },
        summary:
          "Anita described using the app for morning practices and appreciated guided sessions.",
        opportunities: ["finding a practice short enough for a work break"],
        fullSummary: "Uses morning practices daily.",
        generatedAt: new Date().toISOString(),
      },
    }),
    base({
      recordId: "PRC-0004",
      name: "Carlos V.",
      email: "carlos@example.es",
      phone: "",
      meditatorStatus: "New",
      ageGroup: "25–34",
      region: "Spain",
      occupation: "Chef",
      priorFeedback: "",
      featureTag: "Practices",
      status: null,
      callCount: 0,
      lastContactedAt: null,
      scratchpad: "",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0005",
      name: "Meera K.",
      email: "meera@example.com",
      phone: "+91 99887 76655",
      meditatorStatus: "Occasional",
      ageGroup: "18–24",
      region: "India",
      occupation: "Student",
      priorFeedback: "",
      featureTag: "Practices",
      status: "Asked to reschedule",
      callCount: 1,
      lastContactedAt: new Date(Date.now() - 86400000).toISOString(),
      scratchpad: "",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0006",
      name: "David L.",
      email: "david@example.com",
      phone: "+1 555 0100",
      meditatorStatus: "Regular",
      ageGroup: "35–44",
      region: "USA",
      occupation: "Consultant",
      priorFeedback: "",
      featureTag: "Practices",
      status: "Not interested",
      callCount: 1,
      lastContactedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      scratchpad: "",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0007",
      name: "Sneha P.",
      email: "sneha@example.com",
      phone: "+91 90000 11122",
      meditatorStatus: "Regular",
      ageGroup: "25–34",
      region: "India",
      occupation: "Product manager",
      priorFeedback: "",
      featureTag: "Practices",
      status: "Interviewed",
      callCount: 2,
      lastContactedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      scratchpad: "",
      postCallSummary: "Long interview about evening wind-down.",
      snapshot: {
        quickFacts: {
          name: "Sneha P.",
          ageGroup: "25–34",
          region: "India",
          meditatorStatus: "Regular",
          occupation: "Product manager",
          interviewDate: new Date(Date.now() - 2 * 86400000)
            .toISOString()
            .slice(0, 10),
        },
        summary:
          "Sneha uses evening practices to wind down and wants more variety in session length.",
        opportunities: [
          "accessing practices without an internet connection",
          "choosing practice length before starting",
        ],
        fullSummary: "Long interview about evening wind-down.",
        generatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
    }),
    base({
      recordId: "PRC-0008",
      name: "Emma W.",
      email: "emma@example.co.uk",
      phone: "+44 20 7946 0958",
      meditatorStatus: "New",
      ageGroup: "25–34",
      region: "UK",
      occupation: "Nurse",
      priorFeedback: "",
      featureTag: "Practices",
      status: null,
      callCount: 0,
      lastContactedAt: null,
      scratchpad: "",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0009",
      name: "Rajesh T.",
      email: "rajesh@example.com",
      phone: "+91 98111 22334",
      meditatorStatus: "Regular",
      ageGroup: "55+",
      region: "India",
      occupation: "Retired",
      priorFeedback: "Called support once",
      featureTag: "Practices",
      status: "Invalid number",
      callCount: 1,
      lastContactedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      scratchpad: "Number disconnected",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0010",
      name: "Olivia H.",
      email: "olivia@example.au",
      phone: "+61 400 000 111",
      meditatorStatus: "Occasional",
      ageGroup: "35–44",
      region: "Australia",
      occupation: "Writer",
      priorFeedback: "",
      featureTag: "Practices",
      status: "Interviewed",
      callCount: 1,
      lastContactedAt: new Date(Date.now() - 86400000).toISOString(),
      scratchpad: "",
      postCallSummary: "Discussed travel and offline use.",
      snapshot: {
        quickFacts: {
          name: "Olivia H.",
          ageGroup: "35–44",
          region: "Australia",
          meditatorStatus: "Occasional",
          occupation: "Writer",
          interviewDate: new Date(Date.now() - 86400000)
            .toISOString()
            .slice(0, 10),
        },
        summary:
          "Olivia practices when travelling and struggles when connectivity is poor.",
        opportunities: ["practicing while travelling without reliable data"],
        fullSummary: "Discussed travel and offline use.",
        generatedAt: new Date(Date.now() - 86400000).toISOString(),
      },
    }),
    base({
      recordId: "PRC-0011",
      name: "Fatima A.",
      email: "fatima@example.com",
      phone: "+91 88776 65544",
      meditatorStatus: "New",
      ageGroup: "18–24",
      region: "India",
      occupation: "Intern",
      priorFeedback: "",
      featureTag: "Practices",
      status: null,
      callCount: 0,
      lastContactedAt: null,
      scratchpad: "",
      postCallSummary: "",
    }),
    base({
      recordId: "PRC-0012",
      name: "Orphan State",
      email: "",
      phone: "",
      meditatorStatus: "",
      ageGroup: "",
      region: "",
      occupation: "",
      priorFeedback: "",
      featureTag: "Practices",
      status: "No answer",
      callCount: 1,
      lastContactedAt: new Date().toISOString(),
      scratchpad: "Only in AppState",
      postCallSummary: "",
    }),
  ];
}

export function fixtureCandidatesResponse() {
  return {
    candidates: fixtureCandidates(),
    skippedRows: 2,
  };
}
